# Generated by Django 5.1.1 on 2024-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AEFIRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sex', models.CharField(max_length=200)),
                ('Reporter_state_or_province', models.CharField(max_length=200)),
                ('Date_of_report', models.DateField(max_length=200)),
                ('Created_by_organisation_level_2', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
